### ISSUE TITLE
Range/stretch too limited

### ISSUE THREAD

**Issue by afranke** [bragefuglseth/fretboard#10]
It’s impossible to draw chords that span more than four contiguous frets, even though they are not so uncommon. E.g. Every breath you take by The Police is well known for it’s add9 chords that require a 5 frets stretch.

![image](https://github.com/bragefuglseth/fretboard/assets/117241/dc45f302-2883-428b-b91e-3e346bf657f7)

**Comment by bragefuglseth** [comment]
Wow, thanks for the report! The diagram actually had 5 frets to begin with. I simply didn't expect such chords, which is why I reduced the amount. It should be pretty straightforward to add the fifth fret back, I'll get to it tomorrow.

**Comment by bragefuglseth** [comment]
While fixing this, I noticed that the chord database currently doesn't even have that way to play the chord stored. I need to set up some infrastructure to manage the data, but I'll open an chord data issue.
