### ISSUE TITLE
Chord data infrastructure

### ISSUE THREAD

**Issue by bragefuglseth** [bragefuglseth/fretboard#13]
The chord data is currently stored in a monolithic JSON file (`src/chords.json`). This works fine, and I'm not planning on changing it, but it's impossible to manually edit the file. I have a Rust project stored locally that I use to inject changes into it, and it would be nice if this was turned into a little CLI for managing the chord data more conveniently.

**Comment by afranke** [comment]
It may be worth using an external data source for that instead of trying to maintain your own DB. A quick search yields https://github.com/tombatossals/chords-db but there may be others.

**Comment by bragefuglseth** [comment]
That's what I'm doing currently, the database is derived from a similar project. I don't think we'll be able to get around the fact that no chord database is complete.

**Comment by bragefuglseth** [comment]
I've refactored the chords database to use a custom format now. The file is compact and readable enough to be edited directly (even though it spans over 13k lines). This removes the need for a separate editing system.
