### ISSUE TITLE
Bookmark/star chords

### ISSUE THREAD

**Issue by afranke** [bragefuglseth/fretboard#14]
It would be handy to have a way to keep a list of chords to easily jump back to them.

**Comment by bragefuglseth** [comment]
Bookmarking has been implemented, and will be available in Fretboard 2.0!

![Screenshot from 2023-08-27 18-54-54](https://github.com/bragefuglseth/fretboard/assets/91388039/4f045cf6-09a6-4e80-a205-774497112bd9)

![Screenshot from 2023-08-27 18-55-01](https://github.com/bragefuglseth/fretboard/assets/91388039/ae911725-1c5c-437c-af7c-a4e58e6ab7b7)
