### ISSUE TITLE
Inconsistent positioning

### ISSUE THREAD

**Issue by afranke** [bragefuglseth/fretboard#15]
Searching for different chords yields inconsistent positions for close chords.

Compare

![image](https://github.com/bragefuglseth/fretboard/assets/117241/2520b57a-7d71-4a02-a323-c997d7b75a43)

to

![image](https://github.com/bragefuglseth/fretboard/assets/117241/12002215-527d-43a5-848d-de96b8b626fc)

The two should use the same starting fret as they are actually quite close. *1* makes more sense than *2* as starting fret to me.

**Comment by bragefuglseth** [comment]
I’ve tried to make it more generic, but I’ve always ran into problems with that, so this is the solution for now.

**Comment by bragefuglseth** [comment]
Thanks for the help with squashing these endless chord issues!
