### ISSUE TITLE
Emadd9

### ISSUE THREAD

**Issue by afranke** [bragefuglseth/fretboard#18]
(I would have opened a PR, but I couldn’t figure out how chords were sorted and where to add this new one)

**Chord name**
Emadd9

**Current representation**
None

**Suggested representation**

![image](https://github.com/bragefuglseth/fretboard/assets/117241/6a6aeb95-c75e-42da-88de-eb784b243488)

**Comment by bragefuglseth** [comment]
This works one way now, thanks to the new fallback algorithm.

![Screenshot from 2023-07-06 22-56-16](https://github.com/bragefuglseth/fretboard/assets/91388039/21e052eb-2780-46d6-8cb1-4ce67f30d237)
