### ISSUE TITLE
Add minigame for training chrods memory

### ISSUE THREAD

**Issue by Minkiu** [bragefuglseth/fretboard#19]
Probably out of scope, but would be cool to have a mode where the app shows you a chord and the person has to guess which one is it, to train memory of the chords.

**Comment by bragefuglseth** [comment]
Hi, and thanks for your suggestion! While this is a fun idea, you're right in assuming that it's out of scope for the app. I'd still not give up entirely on the concept, though - this could be a separate app, with more guitar or music related games. The existing Fretboard widgetry could probably be reused for it. What about opening an issue in Tobias Bernard's [App Ideas](https://gitlab.gnome.org/bertob/app-ideas) repository?
