### ISSUE TITLE
Translation updates

### ISSUE THREAD

**Issue by bragefuglseth** [bragefuglseth/fretboard#32]
Pinging existing translators: @Gert-dev @phaerrax @ikibastus1 

Fretboard is shaping up for the release of version 3.0 in 3 days, and it has recently gotten some string changes. It would be good if you could have a look at these. I can do a 3.1 release with the remaining translations if you don't have time for it right now, so don't stress.

Something to note is that the "Open" string that was a verb before is now an adjective. I've updated the comment to clarify that.

Translations are now managed on [Weblate](https://hosted.weblate.org/engage/fretboard/), which I hope will make it easier and more straightforward to contribute.

Thanks for your contributions!

**Comment by Gert-dev** [comment]
Would be happy to update the translation :slightly_smiling_face: . Nice that Weblate is now present, makes it slightly easier by not having to download the PO file.

Quick question, though: Dutch shows up as 'empty' and 'needs to be added' on Weblate currently, is that expected? Only Italian and Russian show up.

**Comment by bragefuglseth** [comment]
I’m having some problems with Weblate, will try to get them resolved on Wednesday.

**Comment by bragefuglseth** [comment]
@Gert-dev: The issues should be resolved now 😁

**Comment by daudix-UFO** [comment]
Noticed little typo while translating:

> Italian, Russian, and Dutch translations, making **_Impression_** available in a total of 4 different languages

**Comment by bragefuglseth** [comment]
Oh, I let that one slip! Thanks for noticing!

**Comment by Gert-dev** [comment]
I submitted updated translations on Weblate :slightly_smiling_face: .

**Comment by bragefuglseth** [comment]
Thanks for the help, everyone!
