### ISSUE TITLE
[Feature] Add left-handed view switch

### ISSUE THREAD

**Issue by terrestrian** [bragefuglseth/fretboard#33]
Currently, the way chord diagrams are shown appeals to right handed players. As a left-handed player, this is confusing and it would be really nice to be able look at the chords as reversed.

**Comment by bragefuglseth** [comment]
Seems like it's possible to set the text direction of the chord diagram to RTL to achieve this, so it shouldn't bee to hard to implement. Two radio buttons in the app menu seems like the most sensible way to expose this as a preference.

**Comment by bragefuglseth** [comment]
It was… not that easy. I had to modify the drawing logic and make some architectural changes. But now it's here! This will arrive in Fretboard 4.0.

![Screenshot from 2023-10-04 00-19-13](https://github.com/bragefuglseth/fretboard/assets/91388039/037a5e5a-e003-4bcd-afd9-56a5456af3c5)

![Screenshot from 2023-10-04 00-17-51](https://github.com/bragefuglseth/fretboard/assets/91388039/27f3b2a2-2c59-4d2d-a1dd-eec34898179d)

![Screenshot from 2023-10-04 00-20-46](https://github.com/bragefuglseth/fretboard/assets/91388039/fae4076c-3631-47a6-ace5-8fc3409c4953)

**Comment by terrestrian** [comment]
That looks amazing! Thank you so much for your hard work.
