### ISSUE TITLE
Show enharmonic equivalents

### ISSUE THREAD

**Issue by wjt** [bragefuglseth/fretboard#37]
A♯ and B♭ are the same chord, assuming you don't have a microtonal guitar. Both are understood as input, but only A♯ is shown when you select `x13331` on the fretboard.

It might be nice to show equivalent names for the same chord.

In my experience it is quite rare to see it spelled as A♯, because an A♯ major chord is A♯-C𝄪-E♯. It can happen depending on the key you're in but in isolation… I'd call it B♭. Ditto D♯ / E♭.

**Comment by bragefuglseth** [comment]
This works in main now. I decided to show a clickable indicator in the entry when a chord has an enharmonic equivalent. The button displays the root of the equivalent chord. If you click the indicator, the chord changes to this instead.

![Skjermbilde fra 2023-12-23 12-39-50](https://github.com/bragefuglseth/fretboard/assets/91388039/20635bca-78f9-4d72-b1a9-1afd89058883)
