### ISSUE TITLE
[BUG] Horizontal alignment broken with "Large Text" turned on

### ISSUE THREAD

**Issue by NiklasA95** [bragefuglseth/fretboard#38]
**Describe the bug**
The horizontal alignment of the fretboard in relation to the chord input field breaks if the *Large Text* accessibility option in the gnome settings is selected.

**To Reproduce**
1. Open the Activities overview and start typing Accessibility.
2. Click on Accessibility to open the panel.
3. In the Seeing section, switch the Large Text switch to on.

**Expected behavior**
Same alignment as with the normal text size.

**Screenshots**
![grafik](https://github.com/bragefuglseth/fretboard/assets/38316147/fe426708-d2bf-49a6-a828-927087f1f9a5)

**Comment by bragefuglseth** [comment]
Thanks for reporting! I can immediately see that this is something that slipped through with the libadwaita 1.4 upgrade, where it switched to sized pixels for clamp values. It should be pretty straightforward to fix.

**Comment by NiklasA95** [comment]
Thank you for the fix and this awesome app in general! Glad I could contribute german translations in return.
