### ISSUE TITLE
[BUG] Notes in tooltips don’t follow capo

### ISSUE THREAD

**Issue by afranke** [bragefuglseth/fretboard#47]
**Describe the bug**
Use the v on the right to move up the neck and hover over a fret position. A note will appear on the tooltip. This note is incorrect for the new position, it still shows the note for the “1” position. 

**To Reproduce**
1. Hover over 5th string 3rd fret. Tooltip says C, which is correct.
2. Hit v till position is “3”.
3. Hover over 5th string 3rd fret. Tooltip still says C, when it should say D.

Running Fretboard 6.1 as from Flathub on Fedora.

**Comment by bragefuglseth** [comment]
Can you try that again? The tooltip should in theory take the neck position into account, and I can't reproduce the issue:

![Skjermbilde fra 2024-05-08 13-58-00](https://github.com/bragefuglseth/fretboard/assets/91388039/2e276a71-38e8-4c63-9efd-c6348054d448)

**Comment by bragefuglseth** [comment]
Nevermind, I figured it out. It happens for empty / all-open chords. Thanks for reporting!
