### ISSUE TITLE
Display fretboard as one would be looking at it

### ISSUE THREAD

**Issue by yochananmarqos** [bragefuglseth/fretboard#9]
No one looks at a guitar that way. Any tabulature out there displays it with the head of the guitar on the left as one would be looking at the guitar whilst playing.

**Comment by afranke** [comment]
Except you are not looking at tabs, you are looking at guitar chord diagrams (do a google image search for those three words) and that how they are displayed everywhere.

**Comment by bragefuglseth** [comment]
Hi, and thanks for your suggestion! @afranke is right, the diagram is modeled after a standard chord diagram, not a tabulature. This is a pretty well-known way to display it, and most guitarists are more used to read chords this way. I'll close this issue for now, but feel free to come with objections or clarifications if you have any.
